### PR TITLE
Handle object shorthand

### PR DESCRIPTION
**Pull request by BPScott**
Objects that use the shorthand notation should be stringified as such.

This stops `<div style={{color}} />` being converted to `<div style={{color:color}} />`.

This fixes https://github.com/stylelint/stylelint/issues/4449 / https://github.com/stylelint/stylelint/issues/4485

### CODE REVIEW

**Comment by BPScott** [comment]
Thanks for the merge @gucong3000.

@gucong3000 / @ai:  Any chance of releasing a new version so we can get this fix into stylelint?

**Comment by ai** [comment]
@BPScott I will try to release it a week later when I will finish mu bachelor’s party

**Comment by ai** [comment]
https://github.com/gucong3000/postcss-jsx/pull/68

Release in process (waiting for codecov to merge release commit).

**Comment by ai** [comment]
@BPScott released in 0.36.4.

PostCSS now has an [open collective](https://opencollective.com/postcss/). I can switch from my current open-source projects to a long-term solution for `postcss-jsx` maintenance if some company will donate for it.

**Pull request merged**
